= Installation Guide

This is the long-winded installation guide to explain how to bootstrap a Site
instance.

This is partly for pedagogical purposes.

NOTE: In future it would be a good idea to create a docker image of a pre-installed Site.

== Requirements

Before you start, you'll need to have the following installed:

* Java 17+ (Site uses new Java APIs such as `java.util.HexFormat`)
* https://clojure.org/guides/getting_started[Clojure] and
* https://github.com/babashka/babashka[Babashka] installed on your system.

== Before you start

All these instructions are for Arch Linux, please amend accordingly for your own
platform, if different.

Run each command under your user account (i.e. not as root).

For documentation purposes, we'll assume your Site server will be set up to run
on the host site.test. If you choose another hostname, or are setting up for
production, please amend instructions accordingly.

== Configure your local DNS or /etc/hosts

Edit /etc/hosts to point site.test at 127.0.0.1.

----
# Static table lookup for hostnames.
# See hosts(5) for details.
127.0.0.1	localhost site.test
----

== mkcert

Install mkcert

----
sudo pacman -Sy mkcert
----

----
mkcert -install
----

----
Created a new local CA ðŸ’¥
The local CA is now installed in the system trust store! âš¡ï¸
The local CA is now installed in the Firefox and/or Chrome/Chromium trust store (requires browser restart)! ðŸ¦Š
----

== Install nginx

----
sudo pacman -Sy nginx-mainline
----

== Create private key and cert

Create a new cert for the local development server, and move these into your
nginx config directory.

----
mkcert site.test
sudo mv site.test-key.pem site.test.pem /etc/nginx
----

== Configure nginx

Configure nginx. Use `etc/dev/nginx.conf` as a guide to what to configure. You'll need to reference your private key and cert via the `ssl_certificate` and `ssl_certificate_key` parameters.

----
ssl_certificate      site.test.pem;
ssl_certificate_key  site.test-key.pem;
----

You'll need to increase the size of request bodies you can send through nginx,
the default is too restrictive.

----
client_max_body_size 16M;
----

You'll also need to configure the details of your the origin server (Site).

----
http {
  ...
  client_max_body_size 16M;
  ...
  server {
    ...
    ssl_certificate site.test.pem;
    ssl_certificate_key site.test-key.pem;
    ...
    location / {
      proxy_pass http://localhost:2021;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
  }
}
----

Test your final configuration before you start nginx and fix any errors.

----
sudo nginx -t
----

== Start nginx

Start nginx

----
sudo systemctl enable nginx
sudo systemctl start nginx
----

== Clone this repo

----
$ git clone https://github.com/juxt/site
----

== Configure

There's a sample configuration in `etc` you should copy to `$HOME/.config/site/config.edn`.

----
$ mkdir -p $HOME/.config/site
$ cp site/etc/config.edn $HOME/.config/site/config.edn
----

== Start the server

Start the Site server:

----
$ site/bin/site-server
----

NOTE: Alternatively, if you're familiar with Clojure development, you can start
the server via the `deps.edn` file and simply 'jack-in' with your editor or IDE
as normal.

//// should retain this somewhere else
=== Start multiple instances of the server

If you require multiple Site servers to coexist on the same machine, you can start site passing a different configuration file as follows:

----
$ SITE_CONFIG=/absolute/path/custom-site-config.edn site/bin/site-server
----

In this case please be sure to change the configuration so ports are different and XTDB files are stored in a separate folder than the ones specified in the example configuration file. You'll also need to specify Site host:port when using site commands, for example:

----
$ SITE_BASE_URI=http://localhost:5509 site/bin/site get-token -u admin
----
////

== The REPL

If you've run Site via your development environment and 'jacked-in' you'll
already have a REPL. Proceed to the next step.

If you're running Site with `site/bin/site-server`, you'll need to connect a
terminal to Site to access the REPL. You can do this via port 50505, which is a
socket REPL that Site starts by default.

How you connect to this port is up to you. One way is via `ncat`, but you can replace `ncat` with `telnet`, or `netcat`, depending on what's available for your system.

[NOTE]
--
Arch users can install `ncat` by installing the `nmap` package:

----
$ sudo pacman -Sy nmap
----
--

----
$ ncat localhost 50505
----

[TIP]
--
Prefix the command with `rlwrap` if you have it installed.

----
$ rlwrap ncat localhost 50505
----
--

== Bootstrap required resources

Bootstrap the new system by adding the minimum resources that are required to allow remote access.

----
Site by JUXT. Copyright (c) 2021, JUXT LTD.
Type :repl/quit to exit

site>
----

=== Install the admin app

----
(install-admin-app!)
----

=== Create a person entity to represent yourself

It's good practise to associate actions with individuals carrying them out. This
helps when auditing the system later on.

----
(put! {:xt/id "https://site.test/people/mal"  ; replace 'mal' with your username
       :name "Malcolm Sparks"})
----

=== Create actions

----
(create-action "https://home.test/_site/actions/create-person")
(create-action "https://home.test/_site/actions/create-identity")
----

TODO: create-person

=== Create an entity representing the administration app

TODO: This could/should define scopes

=== Create an entity representing yourself

The entity can contain any details you like, but must of course have an `:xt/id`
as a minimum.


=== Create a subject

----
(put! {:xt/id "urn:site:subject:admin:mal"
       :person "https://home.test/people/mal"})
----

=== Create an access token

Finally, create the access token that has permission to call administrative actions.

----
(create-admin-access-token! "urn:site:subject:admin:mal")
----

== Run the site tool

The site tool is a command-line utility that allows you to remotely administer site.

If you're on MacOS, you will need to install the GNU version of `readlink`. You can do so with brew:
```
brew install coreutils
ln -s /usr/local/bin/readlink /usr/local/bin/readlink
```

We must first get a token that we can use for API access. This process authenticates to the site server using your password.

.Here, replace `admin` with your username (or let it default to your OS username)
----
$ site/bin/site get-token -u admin
----

Now we can use the site tool for remote administration. Try the following:

----
$ site/bin/site list-users
----

== Configure the expiry time for tokens

By default, tokens last for an hour. That can sometimes mean they expire during
work sessions. You can set the expiry time of new tokens via the REPL.

----
(put! (assoc (e "http://localhost:2021/_site/token")  ::pass/expires-in (* 24 3600)))
----
