= Installation Guide
:toc: preamble
:toclevels: 5

This is the long-winded installation guide to explain how to bootstrap a Site
instance.

This is partly for pedagogical purposes. It is a good idea to learn in depth how
Site's builds up its secure foundation. But if you are in a hurry, there are (or will be)
quicker 'install packs' and Docker images that provide shortcuts to setting up a
Site instance.

== Requirements

Before you start, you'll need to have the following installed:

* Java 17+ (Site uses new Java APIs such as `java.util.HexFormat`)
* https://clojure.org/guides/getting_started[Clojure]
* https://github.com/babashka/babashka[Babashka]

== Before you start

All these instructions are for Arch Linux, please amend accordingly for your own
platform, if different.

Run each command under your user account (i.e. not as root).

For documentation purposes, we'll assume your Site server will be set up to run
on the host `site.test`. If you choose another hostname, or are setting up for
production, please amend these instructions accordingly.

== Preparing your development environment for Site

=== Decide on a fully qualified hostname

Site is a web server and is designed to be accessed over the network. Since Site
resources are identified by URIs, you should decide on a hostname in a domain
that you control.

For the purposes of learning, development and local testing, it is a good idea
to use a test hostname, such as `site.test`. These instructions are written
assuming that you've chosen `site.test` as your hostname. If you're using your
own hostname in a domain you control, amend these instructions accordingly.

=== Configure your local DNS or /etc/hosts

To access Site locally for bootstrapping we need to ensure requests to
`site.test` are directed to the local service.

Edit /etc/hosts to direct requests for `site.test` to 127.0.0.1.

----
# Static table lookup for hostnames.
# See hosts(5) for details.
127.0.0.1	localhost site.test
----

=== mkcert

// TODO: Explain why we are doing this

Install mkcert

----
sudo pacman -Sy mkcert
----

----
mkcert -install
----

----
Created a new local CA ðŸ’¥
The local CA is now installed in the system trust store! âš¡ï¸
The local CA is now installed in the Firefox and/or Chrome/Chromium trust store (requires browser restart)! ðŸ¦Š
----

=== Install nginx

----
sudo pacman -Sy nginx-mainline
----

=== Create private key and cert

Create a new cert for the local development server, and move these into your
nginx config directory.

----
mkcert site.test
sudo mv site.test-key.pem site.test.pem /etc/nginx
----

=== Configure nginx

Configure nginx. Use `etc/dev/nginx.conf` as a guide to what to configure. You'll need to reference your private key and cert via the `ssl_certificate` and `ssl_certificate_key` parameters.

----
ssl_certificate      site.test.pem;
ssl_certificate_key  site.test-key.pem;
----

You'll need to increase the size of request bodies you can send through nginx,
the default is too restrictive.

----
client_max_body_size 16M;
----

You'll also need to configure the details of your the origin server (Site).

----
http {
  ...
  client_max_body_size 16M;
  ...
  server {
    ...
    ssl_certificate site.test.pem;
    ssl_certificate_key site.test-key.pem;
    ...
    location / {
      proxy_pass http://localhost:2021;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;
  }
}
----

Test your final configuration before you start nginx and fix any errors.

----
sudo nginx -t
----

=== Start nginx

Start nginx

----
sudo systemctl enable nginx
sudo systemctl start nginx
----

== Install Site

=== Clone this repo

----
$ git clone https://github.com/juxt/site
----

== Configure the Site service

=== Install the configuration file

There's a sample configuration in `etc` you should copy to `$HOME/.config/site/config.edn`.

----
$ mkdir -p $HOME/.config/site
$ cp site/etc/config.edn $HOME/.config/site/config.edn
----

IMPORTANT: If you're aren't using `site.test` as a hostname, edit the
configuration to replace `https://site.test` with the URI that corresponds to
the hostname you have chosen,

== Start the Site server

Start the Site server:

----
$ site/bin/site-server
----

NOTE: Alternatively, if you're familiar with Clojure development, you can start
the server via the `deps.edn` file and simply 'jack-in' with your editor or IDE
as normal.

////

(should retain this somewhere else)

=== Start multiple instances of the server

If you require multiple Site servers to coexist on the same machine, you can start site passing a different configuration file as follows:

----
$ SITE_CONFIG=/absolute/path/custom-site-config.edn site/bin/site-server
----

In this case please be sure to change the configuration so ports are different and XTDB files are stored in a separate folder than the ones specified in the example configuration file. You'll also need to specify Site host:port when using site commands, for example:

----
$ SITE_BASE_URI=http://localhost:5509 site/bin/site get-token -u admin
----
////

== Connect to Site's REPL

If you've run Site via your development environment and 'jacked-in' you'll
already have a REPL. Proceed to the next step.

If you're running Site with `site/bin/site-server`, you'll need to connect a
terminal to Site to access the REPL. You can do this via port `50505`, which is a
socket REPL that Site starts by default.

How you connect to this port is up to you. One way is via `ncat`, but you can replace `ncat` with `telnet`, or `netcat`, depending on what's available for your system.

[NOTE]
--
Arch users can install `ncat` by installing the `nmap` package:

----
$ sudo pacman -Sy nmap
----
--

----
$ ncat localhost 50505
----

[TIP]
--
Prefix the command with `rlwrap` if you have it installed.

----
$ rlwrap ncat localhost 50505
----
--

=== Introducing Site's REPL

----
Site by JUXT. Copyright (c) 2021, JUXT LTD.
Type :repl/quit to exit

site>
----

[TIP]
--
There are a few useful Site REPL commands you should be familiar with:

(ls):: List all resources
(ls <pat>):: List all resources whose URIs match the pattern
(evict! <uri>+):: Kill resource(s) across time
(apply evict! (ls)):: Start over. (Delete everything in the database!)
--

== Bootstrap remote access to Site

A Site instance is a collection of documents, stored in XTDB.

Like XTDB, Site is schemaless and requires that you define your own
documents. However, by included document attributes known to Site (usually in
the `juxt.site.alpha` namespace) Site is able to interpret the documents as web
or API resources, and serve them over HTTP.

We need to set up sufficient resources in the REPL so that we no longer need to
access Site via the REPL.

Secure remote access to Site resources requires an *access token*.

In this section we use the REPL to build up the minimal resources required to
acquire an access token which can let us continue setting up the server
remotely, without requiring further REPL access.

An access token is granted for a *subject* and an *application*, so we'll need
to create those too.

But first, we need to install some preliminary resources into our REPL.

=== Install the capability to call actions

Actions are at the heart of Site:

* Actions allow you to read and write to the database.
* Actions are composeable.
* Actions can call external functions, such as lambdas.
* Actions are restricted to authorized users and applications.
* Actions can be grouped into OAuth2 scopes
* Actions can be exposed to the network, via OpenAPI and GraphQL.

==== Install the `do-action` function

Actions are executed in an XTDB transaction function.

This guarantees consistency, eliminating potential race-conditions. For example,
it's important that any revocations to authorization permissions are fully
processed if they occur before a call to an action.

The transaction function also records every action call in an *audit-log*,
detailing when the action was called, by whom, which entities were affected and,
potentially, other details such as the 'business justification'.

We have to first install the transaction function into the database, so that we
can start to call the actions we will create.

[source,clojure]
.Install the do-action transaction function
----
(install-do-action-fn!)
----

==== Create a REPL subject

Actions are performed by subjects.

A *subject* represents an authenticated person, which will include personal data
as well as details about their login session (e.g. the device they are using,
whether their email address has been verified, whether their login required use
of a second factor, etc.).

To call actions from the REPL, we'll install a subject that can only be used
from the REPL. The `(me)` function returns a special built-in identifier for the
REPL subject. It can't be used remotely.

[source,clojure]
.Add the REPL subject
----
(put! {:xt/id (me)})
----

NOTE: In future we might allow different users using the same REPL to identify
themselves. Of course, REPL users have no restrictions to what they can do, so
this is just for audit purposes among trusted users. Access to the REPL must be
restricted to a very limited set of authorized users.

=== Install the create-action action

[source,clojure]
.Install the create-action action
----
(install-create-action!)
----

=== Install the permission for the REPL subject to call create-action

[source,clojure]
----
(put!
{:xt/id "https://site.test/permissions/repl/create-action"
 ::site/type "Permission"
 ::pass/subject "urn:site:subjects:repl"
 ::pass/action #{"https://site.test/actions/create-action"}
 ::pass/purpose nil
 }
)
----

=== Create 'Alice'

For the purposes of this example, we'll create a person entity to represent the
person. We'll use the name `Alice` but feel free to replace this with your own
personal details.

==== Create an action to create a person

.Creating the create-person action
====

[source,clojure]
.Install the create-person action
----
(do-action
"https://site.test/actions/create-action"
{:xt/id "https://site.test/actions/create-person"
 :juxt.site.alpha/type "Action" <1>
 :juxt.pass.alpha/scope "write:admin" <2>

 :juxt.pass.alpha.malli/args-schema <3>
 [:tuple
   [:map
     [:example/type [:= "Person"]]
     [:example/username [:string]]]]

 :juxt.pass.alpha/process <4>
   [
    [:juxt.pass.alpha.process/update-in [0] 'merge {:example/type "Person"}]
    [:juxt.pass.alpha.malli/validate]
    [:xtdb.api/put]]

 ::pass/rules <5>
 '[
   [(allowed? permission subject action resource)
    [permission ::pass/subject subject]]]}
)
----
<1> An action must have this exact entry
<2> Actions are grouped into OAuth2 scopes
<3> Arguments must conform to this schema
<4> The processing pipeline which transforms arguments into XT transaction operations
<5> An action declares the rules as to who is authorized to call it
====

Calling the `do-action` function results in a *transaction metadata record*
being created in the database. This allows us later to answer questions
regarding the who, when, why and how for each document in the database.

.The *transaction metadata record*
====
A copy of the transaction metadata record is returned as a result of the `do-action` function.

[source,clojure]
----
{:xt/id "urn:site:action-log:115"
:xtdb.api/tx-id 115
 :juxt.pass.alpha/subject "urn:site:subjects:repl"
 :juxt.pass.alpha/action "https://site.test/actions/create-action"
 :juxt.pass.alpha/purpose nil
 :juxt.pass.alpha/puts ["https://site.test/actions/create-person"]
 :juxt.pass.alpha/deletes []
 }
----

====

==== Permit the REPL to call the create-person action

.Adding the permission for the REPL to create a person
====

[source,clojure]
----
(put!
{:xt/id "https://site.test/permissions/repl/create-person"
 ::site/type "Permission"
 ::pass/subject "urn:site:subjects:repl"
 ::pass/action #{"https://site.test/actions/create-person"}
 ::pass/purpose nil
 }
)
----
====

==== Create 'Alice' with the create-person action

.Creating 'Alice'
====

[source,clojure]
----
(do-action "https://site.test/actions/create-person"
  {:xt/id "https://site.test/people/alice"
  :example/name "Alice"})
----
====

=== Create a subject entity to represent Alice's login

==== Create an action to create a subject

.Creating an action for creating the subject
====
[source,clojure]
----
(put!
{:xt/id "https://site.test/actions/create-subject"
 :juxt.site.alpha/type "Action"
 :juxt.pass.alpha/scope "write:admin"
 :juxt.pass.alpha/action-args
 [{:juxt.pass.alpha.malli/schema
   [:map
    [:xt/id [:re "https://site.test/subjects(.+)"]]
    [:example/type [:= "Subject"]]
    [:example/person [:re "https://site.test/people/\\p{Alpha}{2,}"]]]

   :juxt.pass.alpha/process
   [
    [:juxt.pass.alpha/merge {:example/type "Subject"}]
    [:juxt.pass.alpha.malli/validate]]}]

 ::pass/rules
 '[
   [(allowed? permission subject action resource)
    ;; Permission granted to the subject
    [permission ::pass/subject subject]
    ]]})
----
====

==== Permit the REPL to call the create-subject action

.Adding a permission on the create-subject action
====

[source,clojure]
----
(put!
{:xt/id "https://site.test/permissions/repl/create-subject"
 ::site/type "Permission"
 ::pass/subject "urn:site:subjects:repl"
 ::pass/action #{"https://site.test/actions/create-subject"}
 ::pass/purpose nil
 }
)
----
====

==== Call the create-subject action

.Calling the create-subject action
====
[source,clojure]
----
(do-action "https://site.test/actions/create-subject"
  {:xt/id "https://site.test/subjects/alice"
   :example/person "https://site.test/people/alice"})
----
====

=== Register an application

TODO

==== Create an action to register an application

TODO

==== Permit the REPL to call the register-application action

TODO

==== Call the register-application action

TODO

=== Create an access token

TODO

== Run the site tool

The site tool is a command-line utility that allows you to remotely administer site.

****
If you're on MacOS, you will need to install the GNU version of `readlink`. You can do so with brew:
```
brew install coreutils
ln -s /usr/local/bin/readlink /usr/local/bin/readlink
```
****

We must first get a token that we can use for API access. This process authenticates to the site server using your password.

.Here, replace `admin` with your username (or let it default to your OS username)
----
$ site/bin/site get-token -u admin
----

Now we can use the site tool for remote administration. Try the following:

----
$ site/bin/site list-users
----

== Post installation steps

=== Configure the expiry time for tokens

By default, tokens last for an hour. That can sometimes mean they expire during
work sessions. You can set the expiry time of new tokens via the REPL.

----
(put! (assoc (e "http://localhost:2021/_site/token")  ::pass/expires-in (* 24 3600)))
----
