= Actions
:toc: left

== Introduction

== Setup actions

////
(old text)

A Site instance is a collection of documents, stored in XTDB.

Like XTDB, Site is schemaless and requires that you define your own
documents. However, by included document attributes known to Site (usually in
the `juxt.site.alpha` namespace) Site is able to interpret the documents as web
or API resources, and serve them over HTTP.

We need to set up sufficient resources in the REPL so that we no longer need to
access Site via the REPL.

Secure remote access to Site resources requires an *access token*.

In this section we use the REPL to build up the minimal resources required to
acquire an access token which can let us continue setting up the server
remotely, without requiring further REPL access.

An access token is granted for a *subject* and an *application*, so we'll need
to create those too.

But first, we need to install some preliminary resources into our REPL.
////

Site adds the concept of *actions* to XTDB.

Actions make up the layer which mediates, authorizes and records read and write
access to the database.

* Actions are restricted to authorized users and applications.
* Actions run in transaction functions to ensure atomicity and consistency.
* Actions can provide involve input validation.
* Actions leave an audit trail and may trigger alerts.
* Actions can be grouped into OAuth2 scopes.
* Actions are used to build higher-level services, such as OpenAPI and GraphQL operations.

=== Install the `do-action` function

Executing actions in an XTDB transaction function guarantees consistency,
eliminating potential race-conditions. For example, it's important that any
revocation of a permission is applied if it is submitted before a request that
requires the permission.

The transaction function also records every action call in an *audit-log*,
detailing when the action was called, by whom, which entities were affected and,
potentially, other details such as the 'business justification'.

We must first install the transaction function into the database, so that we can
call actions we create.

[source,clojure]
.Install the do-action transaction function
----
(install-do-action-fn!)
----

=== Create a subject representing the REPL user

Actions are performed by **subject**s.

A subject represents an authenticated person, which will include personal data
as well as details about their login session (e.g. the device they are using,
whether their email address has been verified, whether their login required use
of a second factor, etc.).

To call actions from the REPL, we'll install a subject that can only be used
from the REPL. The `(me)` function returns a special built-in identifier for the
REPL subject.

[source,clojure]
.Add the REPL subject
----
(put! {:xt/id (me)})
----

NOTE: In future we might allow different users using the same REPL to identify
themselves. Of course, REPL users have no restrictions to what they can do, so
this is just for audit purposes among trusted users. Access to the REPL must be
restricted to a very limited set of authorized users.

=== Define the create-action action

We install the `create-action` action. This is the one action that has to be put
directly into the database because we don't have a way of creating actions yet!

[source,clojure]
.Install the create-action action
----
(install-create-action!)
----

[source,clojure]
.Permit the create-action action
----
(permit-create-action!)
----

=== Define the grant-permission action

Now that we have our `create-action` function installed we can use it to create
an action that will grant permissions.

----
(install-grant-permission-action!)
----

Note that this function will return a copy of the *transaction metadata record*
for the transaction that created the grant-permission action.

.Transaction Metadata Records
****

Whenever an action is called, the `do-action` transaction function is executed
which results in a *transaction metadata record* being created in the
database. If the action is denied, or if errors occur when the action is
executed, details will be recorded in the transaction metadata.

This allows us later to answer questions as to whether an action was allowed or
denied, with an explanation. We will also be able to answer questions regarding
the who, when, why and how for each document in the database.

.A *transaction metadata record*
====
A copy of the transaction metadata record is returned as a result of the `do-action` function.

[source,clojure]
----
{:xt/id "urn:site:action-log:134"
 :xtdb.api/tx-id 134
 :juxt.pass.alpha/subject "urn:site:subjects:repl"
 :juxt.pass.alpha/action "https://site.test/actions/create-action"
 :juxt.pass.alpha/purpose nil
 :juxt.pass.alpha/puts ["https://site.test/actions/grant-permission"]
 :juxt.pass.alpha/deletes []}
----
====
****

=== Permit REPL access to the grant permission action

We need to permit our REPL user to call this grant-permission action, and this permission too
needs to be put directly into the database since we don't yet have a way of
granting permissions!

.Granting the REPL user the permission to grant permssions.
----
(permit-grant-permission-action!)
----
