= Actions
:toc: left

Site introduces the concept of *actions* which are the foundational primitives
on which everything else in Site is built.

== Introduction

Actions authorize all reads and writes to the database. Actions also record all
writes, and some reads from the database.

////
TODO: Use xrefs from these bullet-points to more detailed explanations, such
that these set of items can become a launchpad for diving into the
documentation.
////

* Actions run in transaction functions to ensure atomicity and consistency.

* Actions can provide involve input validation.

* Actions define their access control in rules, which are sufficient powerful to
  model any access control policy (RBAC, ABAC, PBAC, etc.)

* Actions leave an audit trail and may trigger alerts.

* Actions can be grouped into OAuth2 scopes.

* Actions can be exposed to the network, using OpenAPI and/or GraphQL operations.

* Actions can cause side-effects (e.g. lambda functions).

* Actions decouple network APIs from lower-level effects. For example, an API
  implementation can use a 'send-email', without having to know the
  implementation details of sending emails.

////
(old text)

A Site instance is a collection of documents, stored in XTDB.

Like XTDB, Site is schemaless and requires that you define your own
documents. However, by included document attributes known to Site (usually in
the `juxt.site.alpha` namespace) Site is able to interpret the documents as web
or API resources, and serve them over HTTP.

We need to set up sufficient resources in the REPL so that we no longer need to
access Site via the REPL.

Secure remote access to Site resources requires an *access token*.

In this section we use the REPL to build up the minimal resources required to
acquire an access token which can let us continue setting up the server
remotely, without requiring further REPL access.

An access token is granted for a *subject* and an *application*, so we'll need
to create those too.

But first, we need to install some preliminary resources into our REPL.
////

=== Data consistency

Actions that modify the database are run in a transaction function. This ensures
that the authorization check is made at the latest possible point, just before
the database is potentially modified. This avoids any potential for
race-conditions, for example, if the authorization to perform an action is
revoked just before the action is called.

=== Audit logging

Whenever an action is called, the `do-action` transaction function is executed
which results in a *transaction metadata record* being created in the
database.

This makes it possible to find out when an action was called, by whom, which
entities were affected and, potentially, other details such as the 'business
justification'.

If the action is denied, or if errors occur when the action is executed, details
will be recorded in the transaction metadata.

This allows us later to answer questions as to whether an action was allowed or
denied, with an explanation. We will also be able to answer questions regarding
the who, when, why and how for each document in the database.

A copy of the transaction metadata record is returned as a result of the
`do-action` function, as shown in <<transaction-metadata-record-example>>.

[[transaction-metadata-record-example]]
.A *transaction metadata record*
====

[source,clojure]
----
{:xt/id "urn:site:action-log:134"
 :xtdb.api/tx-id 134
 :juxt.pass.alpha/subject "urn:site:subjects:repl"
 :juxt.pass.alpha/action "https://site.test/actions/create-action"
 :juxt.pass.alpha/purpose nil
 :juxt.pass.alpha/puts ["https://site.test/actions/grant-permission"]
 :juxt.pass.alpha/deletes []}
----
====

== Installation steps

We must first install some entities into Site.

The first is an action called `create-action`. This action will allow us to
create more actions.

== Defining the create-action action

We install the `create-action` action. This is the one action that has to be put
directly into the database because we don't have a way of creating actions yet!

.Install the create-action action
[[install-create-action-action]]
--
[source,clojure]
----
include::../../dev/demo.clj[tag=install-create-action!,indent=0]
----
<1> foo
--

=== Installing the `do-action` function

We must first install the transaction function into the database, so that we can
call actions we create.

[source,clojure]
.Install the do-action transaction function
----
include::../../dev/demo.clj[tag=install-do-action-fn!,indent=0]
----
