= Authentication
:toc: left

== Add a trusted identity provider

Site does not store user credentials but requires that you provide one or more trusted identity providers that are compatible with OpenID Connect Discovery. Examples include https://www.keycloak.org/[Keycloak], https://auth0.com/[Auth0], Okta, Google, https://aws.amazon.com/cognito/[AWS Cognito] and many more.

.Adding Auth0 as an OpenID Connect provider
====
Create an account with Auth0 and note the Auth0 tenant (domain).

[source,clojure]
----
(add-openid-provider! "https://juxt.eu.auth0.com")
----

Create an app client and take a note of the client-id and client-secret.

[source,clojure]
----
(add-openid-login!
:name "auth0"
:provider "https://juxt.eu.auth0.com/.well-known/openid-configuration"
:client-id "<client-id>"
:client-secret "<client-secret>")
----
====

== Create users

=== Create a user

To remotely access the system, we'll first have to build a user.

For this example, we'll model a user as a combination of:

- A *person*,

- A person's *identity*, as issued from a trusted entity such as an OAuth2
  Authorization Server, Identity Provider or equivalent,

- A *subject* which represents the person's current *session*, including details
  of how they logged in.

NOTE: We don't have to model a user this way, and for some applications this
might be overly simplistic. Site allows you to model your own users as you see
fit, as long as there is something to represent a *subject*.

For the purposes of this example, we'll create a person entity to represent the
person.

We'll use the name `Alice` but feel free to replace this with your own personal
details.

==== Create an action to create a person

First, we'll need to create an action which will create our person entity.

.Creating the create-person action
====

[source,clojure]
.Install the create-person action
----
(create-action!
{:xt/id "https://site.test/actions/create-person" <1>
 :juxt.pass.alpha/scope "write:admin" <2>

 :juxt.pass.alpha.malli/args-schema <3>
 [:tuple
   [:map
     [:xt/id [:re "https://site.test/people/\\p{Alpha}{2,}"]]
     [:example/type [:= "Person"]]
     [:example/name [:string]]]]

 :juxt.pass.alpha/process <4>
 [
  [:juxt.pass.alpha.process/update-in [0] 'merge {:example/type "Person"}]
  [:juxt.pass.alpha.malli/validate]
  [:xtdb.api/put]]

 ::pass/rules <5>
 '[
   [(allowed? permission subject action resource)
    [permission ::pass/subject subject]]]}
)
----
<1> You can choose any id here but it's a good idea to keep to a convention
<2> Actions are grouped into OAuth2 scopes
<3> Arguments must conform to this schema
<4> The processing pipeline which transforms arguments into XT transaction operations
<5> An action declares the rules as to who is authorized to call it
====

==== Permit the REPL to call the create-person action

.Adding the permission for the REPL to create a person
====

[source,clojure]
----
(grant-permission!
{:xt/id "https://site.test/permissions/repl/create-person"
 ::pass/subject (me)
 ::pass/action #{"https://site.test/actions/create-person"}
 ::pass/purpose nil
 }
)
----
====

==== Create 'Alice' with the create-person action

.Creating 'Alice'
====

[source,clojure]
----
(do-action "https://site.test/actions/create-person"
  {:xt/id "https://site.test/people/alice"
  :example/name "Alice"})
----
====

=== Create an identity to identify Alice

Now we need to register an *identity* for Alice so that we can trust her.

////
.Keep this for when we need to create a subject for Alice
****
We do this because we may want our rules to take into account other aspects of
Alice's session rather than just the fact that it belongs to Alice. For example,
we may want some actions to be denied if Alice is logging in from an insecure
location or from a different country.
****
////

==== Create an action to create a identity

.Creating an action for creating the identity
====
[source,clojure]
----
(create-action!
 {:xt/id "https://site.test/actions/create-identity"
  :juxt.pass.alpha/scope "write:admin"

  :juxt.pass.alpha.malli/args-schema
  [:tuple
   [:map
    [:juxt.site.alpha/type [:= "Identity"]]
    [:example/person [:re "https://site.test/people/\\p{Alpha}{2,}"]]]]

  :juxt.pass.alpha/process
  [
   [:juxt.pass.alpha.process/update-in [0] 'merge {:juxt.site.alpha/type "Identity"}]
   [:juxt.pass.alpha.malli/validate]
   [:xtdb.api/put]]

  :juxt.pass.alpha/rules
  '[
    [(allowed? permission subject action resource)
     [permission :juxt.pass.alpha/subject subject]]]})
----
====

==== Permit the REPL to call the create-identity action

.Adding a permission on the create-identity action
====

[source,clojure]
----
(grant-permission!
 {:xt/id "https://site.test/permissions/repl/create-identity"
  :juxt.pass.alpha/subject "urn:site:subjects:repl"
  :juxt.pass.alpha/action #{"https://site.test/actions/create-identity"}
  :juxt.pass.alpha/purpose nil})
----
====

==== Call the create-identity action

.Calling the create-identity action
====
[source,clojure]
----
(do-action
 "https://site.test/actions/create-identity"
 {:xt/id "https://site.test/identities/alice"
  :example/person "https://site.test/people/alice"
  :juxt.pass.jwt/iss "https://juxt.eu.auth0.com/"
  :juxt.pass.jwt/sub "github|123456"})
----
====

////
might not be necessary

=== Register an application

TODO

==== Create an action to register an application

TODO

==== Permit the REPL to call the register-application action

TODO

==== Call the register-application action

TODO

////

=== Create an access token

TODO

== Understanding the authentication flow

Site must acquire an ID_TOKEN in order to identify a subject.

The way it does this is by communicate with an identity provider.

In the language of OAuth2, Site takes on the role of a Client and the Identity
Provider takes on the role of the Authorization Server.

Once Site has established confidence in the subject's claims, it can then
proceed to authorize access to its resources.

.How Site gets an ID_TOKEN
[plantuml,authentication-flow,png]
....
skinparam monochrome true
autonumber

actor Alice as user
participant browser

box Site
participant Client as site
database XT
end box

box Identity Provider
participant "/authorize" as auth
participant "/login" as login
participant "/token" as token
end box

browser -> site: GET /login
site <- XT: Look up config of\nIdentity Provider
site -> XT: Create session cookie,\nwith state value
site -> browser: Set session cookie,\nredirect to /authorize
browser -> auth: GET /authorize, no session cookie
note over site: We are asking Alice to authorize Site's access to her details
note over auth: Who is this?
auth -> browser: Redirect to /login
browser -> login: GET /login
login -> browser: login page HTML
user -> browser: Enter password
browser -> login: POST
note over login: OK, it's Alice
login -> browser: Set session cookie, redirect to /authorize
browser -> auth: GET /authorize, this time with cookie
auth -> browser: Do you want to authorize Site?
user -> browser: Yes please!
browser -> auth: Yes
auth -> browser: Redirect to Site with this code
browser -> site: Here is the code and state
site <- XT: Check state value
site -> token: POST code
token -> site: ID_TOKEN containing\nAlice's details
site -> XT: Add ID_TOKEN to session
site -> browser: Upgrade session cookie

....
