= Introduction
:toc: left

== What is Site?

Site is a place to keep records.

Site provides access to records over HTTPS. To supoprt this, each record is
identified with a Uniform Resource Identifier (URIs) and becomes a web resource.

Site allows applications to manage these resources, via user-defined APIs.

Site can protect resources from unauthorized access, and log access to resources
when required.

Site retains a full history.

== This book

This book teaches Site from 'the ground up'.

This is partly for pedagogical purposes. It is a good idea to learn in depth how
Site's builds up its secure foundation.

But if you are in a hurry, there are (or will be) quicker 'install packs' and
Docker images that provide shortcuts to setting up a Site instance.

== Conventions used in this book

=== Reader interventions

We use an admonition with an exclamation mark to indicate where we require that
you act, and do something. In code, the exclamation mark is commonly used to
indicate a side-effect. In this book, the side-effect is carried out by the
reader!

====
IMPORTANT: Make tea!
====

=== Proper nouns

Where nouns are well specified and appear in a glossary, we write them as proper
nouns rather than common nouns. Whenever such a noun is capitalised, it has the
formal meaning as defined in the <<glossary>> rather than its common
meaning. This allows us to use common nouns with less risk of confusion.
