= Resources
:toc: left

== Introduction

Resources in Site are web resources, as per https://httpwg.org/specs/rfc7231.html#resources[RFC 7231].

Resourse are identified by a URI. When resources are stored in XT, the
resource's URI is the `:xt/id` attribute.

A web resource is a series of states across time, just like an XT entity.

In this section we'll create a basic plain-text public resource containing the
classic greeting.

== Anatomy of a Site resource

NOTE: TODO: Describe the key entries of the XT document that represents a Site
resource.

== Publishing public resources

Before we can create the resource, we need to define an action that lets us do so.

In many organisations, publishing information to the public web may well be a
restricted operation so we'll model it as such, and define an action called
`https://site.test/actions/put-immutable-public-resource`.

[source,clojure]
----
include::../../dev/demo.clj[tag=create-action-put-immutable-public-resource!,indent=0]
----
<1> We'll put this action in the `write:resource` scope
<2> We add (or override) the HTTP methods allowed on this resource. Each entry is a mapping from an allowed method to a set of actions. This restricts the search for permissions to a set of actions. The fact that we don't specify any methods such as PUT, POST or DELETE that will change the resource is the reason we've named this action as creating an immutable public resource.
<3> This rule ensures this action must be specifically granted to someone.

Now we must grant permission for our REPL user to use this action:

[source,clojure]
----
include::../../dev/demo.clj[tag=grant-permission-to-call-action-put-immutable-public-resource!,indent=0]
----

When Site receives a web request for a resource it will look for a `juxt.site.alpha/methods`
entry which indicates which action or actions should be used when seeking
permission.

In effect, this allows the resource to indicate which rules are to be used
in determining whether a user can access the resource.

A `GET` request on our Hello World resource implies will correspond to the
`https://site.test/actions/get-public-resource` action, so we'll need to create
that now.

[source,clojure]
----
include::../../dev/demo.clj[tag=create-action-get-public-resource!,indent=0]
----
<1> We use a more appropriate scope that better reflects this action.
<2> This is a very weak rule that matches a particular permission.

A permission document _must_ exist for every case.
The rule of the `http://site.test/actions/get-public-resource` requires a specific permission to exist, so we need to create that now.

[source,clojure]
----
include::../../dev/demo.clj[tag=grant-permission-to-call-get-public-resource!,indent=0]
----

=== Hello World!

To demonstrate our new `put-immutable-public-resource` action, let's publish a
resource that will print `Hello World!` on a web page.

.Creating a simple public 'Hello World' resource
[[hello-world-example]]
====
[source,clojure]
----
include::../../dev/demo.clj[tag=create-hello-world-resource!,indent=0]
----

Now we can test access with `curl`:

----
curl -i https://site.test/hello
----

You should get a `200` response similar to this:

----
HTTP/1.1 200 OK
Server: nginx/1.20.2
Date: Mon, 28 Mar 2022 00:15:15 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
site-request-id: https://site.test/_site/requests/f8a1a799c72e28ec2409c1d5
permissions-policy: interest-cohort=()

Hello World!
----
====

== Publishing private resources

Now let's publish an immutable private resource which can only be seen by an
authenticated user.

We'll need an action to publish a private resource.

----
include::../../dev/demo.clj[tag=create-action-put-immutable-private-resource!,indent=0]
----

We'll grant this permission to our REPL user.

----
include::../../dev/demo.clj[tag=grant-permission-to-put-immutable-private-resource!,indent=0]
----

Now we'll create the action that is used to get a private resource. The rules
mandate that a permission has been granted on a specific resource and the
subject is not nil.

----
include::../../dev/demo.clj[tag=create-action-get-private-resource,indent=0]
----

NOTE: TODO: Now we need to create the actual private resource

NOTE: TODO: Trigger a 401

NOTE: TODO: Install a 401 error page with a redirect to login

NOTE: TODO: Grant a permission upon it.
