[[ch-subjects]]
= Subjects
:toc: left
:experimental:

(((subject, definition)))
An Action is performed by a *Subject*. A Subject represents the _who_ of a
transaction, a Permission or a decision.

In Site, the Subject is a database document automatically created when the user
authenticates and represents a *user login*. This document has the
`juxt.site.alpha/type` attribute value set to "`Subject`".

(((identity, defintiion)))
A Subject always references an *Identity*, with the `juxt.pass.alpha/identity`
attribute. The Identity tells us _who_ the user is. But a Subject might also
include information such as:

* When the user logged in
* Where the user logged in from
* The number and type of authentication factors which were used
* Whether the user's claimed email address has been verified

An Identity contains information that can uniquely identify a User, such as the
user's login credentials, company-wide username, email address, Twitter handle
or a reference to an external identity issued by another authority.

The Identity _can_ contain information about the individual user, but since
user's often have multiple identities, it is a good idea to use an attribute to
reference another document representing the User. Any choices here will be
reflected in the Rules contained in the Actions.

<<subject-model>> shows how these documents relate.

.Subjects and Identities
[[subject-model]]
[plantuml,subject-model,png]
....
skinparam monochrome true
@startjson
include::subject-model.json[]
@endjson
....

== Create a Subject to represent the REPL

To create and call actions from the REPL, we'll install a special Subject that can only be used
from the REPL.

The `(me)` function returns a special built-in identifier for the REPL subject.

.Put a Subject to represent the REPL user
[[example-put-repl-subject]]
====
[source,clojure]
----
include::../../dev/demo.clj[tag=install-repl-user!,indent=0]
----
====

[IMPORTANT]
--
Copy the code from <<example-put-repl-subject>> and paste it into the REPL. Evalute it.
--


[source,clojure]
.Permit the create-action action
----
include::../../dev/demo.clj[tag=permit-create-action!,indent=0]
----

NOTE: In future we might allow different users using the same REPL to identify
themselves. Of course, REPL users have no restrictions to what they can do, so
this is just for audit purposes among trusted users. Access to the REPL must be
restricted to a very limited set of authorized users.
