= Users
:toc: left
:experimental:

(((user, document structure)))
A User is a database document, with the `juxt.site.alpha/type` attribute value
set to "`User`", as detailed in <<user-doc-structure>>.

NOTE: Developer note: It's possible that we can relax the `juxt.site.alpha/type`
constraint across Site. We need to analyse if and where it's being used in the
code and see how we can remove Site's dependency on it.

.Document structure of a User
[[user-doc-structure]]
[%header,cols="2l,3d,1"]
|===
|Attribute|Value|Required?

|:xt/id
|Users are resources, so this is a URI.
s|Required

|:juxt.site.alpha/type
l|"User"
s|Required
|===

== User Identities

(((user identity, definition)))
An Identity contains information that can uniquely identify a User, such as the
user's login credentials, company-wide username, email address, Twitter handle
or a reference to an external identity issued by another authority.

(((user identity, document structure)))
An Identity always references a *User*, with the `juxt.pass.alpha/user`
attribute, as detailed in <<identity-doc-structure>>.

.Document structure of an Identity
[[identity-doc-structure]]
[%header,cols="2l,3d,1"]
|===
|Attribute|Value|Required?

|:xt/id
|Identities are resources, so this is a URI.
s|Required

|:juxt.site.alpha/type
l|"Identity"
s|Required

|:juxt.pass.alpha/user
|A reference to a User.
s|Required

|:juxt.pass.jwt/iss
|The OpenID Issuer Identifier, e.g. "+https://juxt.eu.auth0.com/+"
|Optional

|:juxt.pass.jwt/sub
|The OpenID Subject Identifier, e.g. "+johndoe+"
|Optional
|===

== Subjects

(((subject, definition)))
In Site, a *Subject* is a database document automatically created when the user
authenticates and represents a *user login*. This document has the
`juxt.site.alpha/type` attribute value set to "`Subject`".

(((subject, relationship to user identity)))
A Subject always references an *Identity*, with the `juxt.pass.alpha/identity`
attribute.

The Identity tells us _who_ the user is, but a Subject might also
include information such as:

* When the user logged in
* Where the user logged in from
* The number and type of authentication factors which were used
* Whether the user's claimed email address has been verified

(((user identity, document structure)))
<<subject-doc-structure>> lists some recognised attributes of a Subject.

.Document structure of a Subject
[[subject-doc-structure]]
[%header,cols="2l,3d,1"]
|===
|Attribute|Value|Required?

|:xt/id
|Subjects are resources, so this is a URI.
s|Required

|:juxt.site.alpha/type
l|"Subject"
s|Required

|:juxt.pass.alpha/identity
|A reference to an Identity.
s|Required
|===

<<user-model>> shows an example of how a Subject may relate to an Identity, and
how an Identity, in turn, may relate to a User.

.A possible relationship between a Users Subject and Identity
[[user-model]]
====
[plantuml,user-model,png]
....
skinparam monochrome true
@startjson
include::user-model.json[]
@endjson
....
====

== Create a User

Since an Action are performed by a *User*, we need to create a user to start
invoking our actions.

<<example-put-user>> demonstrates how to create a user called "Malcolm Sparks", with an associated identity.

.Create your own User
[[example-put-user]]
====
[source,clojure]
----
include::../../dev/demo.clj[tag=install-user!,indent=0]
----
====

[IMPORTANT]
--
. Copy the code from <<example-put-user>> and paste it into an editor.
. Personalise it according to your own user details.
. Copy the result into a REPL and evaluate it.
--
